build:
  web:
    privileged: true
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - cd web
      - docker build -f Dockerfile -t lewisoaten/devops-web:${DRONE_COMMIT} .
      - docker save -o devops-web-${DRONE_COMMIT}.tar lewisoaten/devops-web:${DRONE_COMMIT}

deploy:
  sftp:
    host: ip-10-0-2-10.eu-west-1.compute.internal
    port: 22
    username: ubuntu
    files:
      - devops-web-${DRONE_COMMIT}.tar

compose:
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "vfs"
