build:
  web:
    privileged: true
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - cd web
      - docker build -f Dockerfile -t lewisoaten/devops-web:${DRONE_COMMIT} .
    when:
      event: push

compose:
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "vfs"
