publish:
  docker:
    username: $$DOCKER_HUB_USERNAME
    password: $$DOCKER_HUB_PASSWORD
    email: $$DOCKER_HUB_EMAIL
    repo: lewisoaten/devops-web
    tag: latest
    file: web/Dockerfile
    insecure: false
    privileged: true
