build:
  web:
    privileged: true
    image: centos:latest
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - cd web
      - docker build -t web:latest .
      - docker save -o devops-web-latest.tar web:latest
